# Generated by Django 6.0.1 on 2026-01-11 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='factory',
            field=models.ForeignKey(limit_choices_to={'role': 'factory'}, on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidenceversion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_versions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidenceversion',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='compliance.evidence'),
        ),
        migrations.AddField(
            model_name='request',
            name='buyer',
            field=models.ForeignKey(limit_choices_to={'role': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='factory',
            field=models.ForeignKey(limit_choices_to={'role': 'factory'}, on_delete=django.db.models.deletion.CASCADE, related_name='factory_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='evidence_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_items', to='compliance.evidenceversion'),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='fulfilled_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'factory'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compliance.request'),
        ),
        migrations.AlterUniqueTogether(
            name='evidenceversion',
            unique_together={('evidence', 'version_number')},
        ),
    ]
